HDRUK/gateway-web

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/ApplicantActionButtons/ApplicantActionButtons.js

- Removed submit application button when application has already been submitted
- Made contributor autocomplete readOnly in readOnly circumstances
- Fixed state persistence of contributor selection so that previous state is kept if the modal is closed (except if save changes has been clicked)

IG-655 Design Review Fixes

---

src/pages/collections/AddCollectionPage.js
src/pages/collections/EditCollectionPage.js

Image URLs cant always guarantee to have an extension and the existing regex is OTT, changed to make sure this is a full URL with accepted characters and not much more.

SUPP-247 - image urls cant always guarantee to have an extension

---

src/pages/dashboard/Workflows/AddEditWorkflow.js

Description for deadline on workflow builder showed a notify period 1 day before the deadline. This has been updated to 3 days before, matching the value in the backend and the validation on the frontend.

tweak-to-deadline

---

src/pages/dataset/DatasetPage.js

**Sentry Issue**
[https://sentry.io/organizations/hdruk-gateway-16/issues/2039909637/events/6689e53112034150a0af9b7e0c318450/](url)
**Cause**
Incorrect undefined check (missing 'typeof') allowing code execution to attempt to find the length of an undefined/null reference.
**Resolution**
Fixed undefined checks using Lodash 'nil' check which returns true if a reference is either null or undefined.

Fixed undefined checks for phenotype data

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js

Fix applied to keep about application in read only mode when editing a previous submission.  This prevents the user from changing details such as datasets applied for, application name etc.

Fix DAR 'about application' section edit mode post submission

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/DataAccessRequest.scss
src/pages/DataAccessRequest/components/CustodianActionButtons/CustodianActionButtons.js

Browser compatibility testing showed Safari's inability to render option tags inside only select parents, meaning that the React-bootstrap Dropdown does not work properly.
The fix was to change the option elements to clickable divs and apply to appropriate styling for it to render again.
Now re-tested in all browsers.

DAR - Make a decision dropdown - Fix display issue in Safari

---

src/css/styles.scss
src/pages/course/Course.scss
src/pages/dashboard/Dashboard.scss

Temporary fix to ensure there are checkboxes on the complete registration page. Browsers that don't display the custom checkbox will display the browser standard one instead. Browsers like Chrome that have no problem with it will still display the custom checkbox as usual.

Ensuring that there is checkboxes on the complete registration page - HF

---

src/css/styles.scss

[IG-1204 IE - Registration fix rednering on selected dropdown for sector](https://hdruk.atlassian.net/browse/IG-1204?atlOrigin=eyJpIjoiMTdiYWJmZDI3MzRjNGFmMmIxYWU4YjRlYWRkYWRkN2MiLCJwIjoiaiJ9)
Testing via PA browserstack
Rendering issue with account **'Sector'** dropdown.
The issue is visible by logging in and navigating to user account and viewing **‘Sector'** within **IE 11**. The main cause is with the absolute position value set on the value class, IE is rendering it correctly to it’s browsers document object model. There should be a top and left property added to this class within the CSS, it is standard practice that an absolute position must have a property for each axis (x, y or top, right, bottom, left). The reason for this is, to set it in relation to the parent containing div …

IG-1204 IE - Registration fix rednering on selected dropdown for sector

---

package.json

Winterfell package.json update
Winterfell was using a development branch FlagsHover in our dev branch (package.json). The  branch HDWIN-008-FlagsHover has now been merged into HDRUK>Winterfell (master). The resource has been update to reflect.

Winterfell Package.json update

---

src/pages/paper/PaperPage.js
src/pages/tool/ToolPage.js

[SUPP 339](https://hdruk.atlassian.net/browse/SUPP-339?atlOrigin=eyJpIjoiYzA0NjgyOGZmYzkzNDFjYTgwZGFiZDNlY2IxMjIwMDIiLCJwIjoiaiJ9)
An small issue was reported that the Uploader field within Tool, Projects and Papers was outputting the numeric user id based in tools > users. A solution has been implemented to declare a new field called **uploader** which concats **$uploaderIs** and selects out the users **firstname** and **lastname** 
Backend API update
Frontend

SUPP-339 - Project uploader shown as ID NOT name

---

src/pages/dataset/components/AboutCardElement.js

AboutCardElement was missing Linkify
Links were broken on datasets which used the AboutCardElement so this PR wraps the necessary information to ensure that hyperlinks are created once the data is rendered.

Clickable links on datasets regression fix

---

src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js

- Changed storage of NCS project within DAR application from _id to id, in order to provide a working hyperlink when submitting the application.  This is due to the website accepting the numeric id as the route value to identify the correct project to load.

SUPP-369 - On DAR submission, custodian emails do not contain NCS project details

---

src/pages/dashboard/Account.js

- Added auth check around display of workflows navigation item.  User should be a manager of the selected team in order to view this part of the site.  Existing backend implementation returned a 401 on attempting navigation.

Hiding workflows navigation item for team members without manager role

---

src/pages/dashboard/Dashboard.scss

-Added text wrapping to allow navigation dropdown to show longer team names without overflowing, default css property was no-wrap

Fixed overflow for team dropdown in dashboard area

---

src/pages/DataAccessRequest/components/TypeaheadDataset/TypeaheadDataset.js

- The dataset autocomplete component had a fail over to use the abstract of the dataset in the event the description property was missing. This was throwing an error as the path was incorrect in the case of the failover. This PR fixed the path and adds a further default value in the event both description and abstract are missing.

SUPP-389 - Fixed error thrown in DAR selection of multiple datasets if any dataset is missing a required value

---

src/pages/search/Filters.js

As said in title, I've added aria-labels to each filter link on the search page. This is to primarily help support screen readers in their use on the gateway.

Adding aria-labels to filters to enhance screen reader compatibility

---

src/HDRRouter.js
src/pages/dashboard/Account.js
src/pages/dashboard/AccountAdvancedSearch.js
src/pages/dashboard/AdvancedSearchRequestAccessModal.js
src/pages/dashboard/AdvancedSearchRequestAccessModal.scss
src/pages/dashboard/AdvancedSearchTAndCsModal.js
src/pages/dashboard/AdvancedSearchTAndCsModal.scss
test/AccountAdvancedSearch.test.js

EPIC: 
IG-723
Description:
User validation logic for Cohort Discovery (version 1).
A user should only be able to acces RQuest from the gateway if they are both
1. Authorised by HDR via an advancedSearchAccessRole
2. Have accepted the T&C's of advanced search
An Open Athens user will be automatically assigned an access role upon attempting to access advanced search.  Other users will be presented with a modal that will redirect them to create a Jira ticket requesting for an HDR member to approve them.  (In v1 this involves manually adding a role to that user in the database).
If a user has been assigned the role, the next time they attempt to access advanced search they will be presented with a T&C's modal.  Upon accepting this they will be redirected to the RQuest test site hosted by HDR.

User validation for advanced search

---

src/css/styles.scss
src/pages/collections/CollectionPage.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/course/CoursePage.js
src/pages/paper/PaperPage.js
src/pages/project/ProjectPage.js
src/pages/tool/ToolPage.js

[SUPP-419](https://hdruk.atlassian.net/browse/SUPP-419)
Request to change the rendering of words within our collections, tools, papers, projects as requested by HDRUK. Words split across multiple lines as a direct result of our text-break class which was introduced to handle URLS. The new CSS will target a div specifically and only a[href] attributes which need to break if they are lengthy and have the potential to break the overall layout.
Tested using UATBeta database via localhost, various tools that used ReactMarkdown and anchors within these  areas.
- Tools, created and viewed ALL OK /tool/4764541661155508
- Projects, created and viewed  ALL OK  /project/5377703726941019
-  Papers, updated and viewed ALL OK, /paper/5379076543724559
- Courses, updated and viewed ALL OK, …

SUPP-419 Collection render issue

---

src/pages/dashboard/AccountAdvancedSearch.js
src/pages/dashboard/AdvancedSearchTAndCsModal.js

Text updates only for exit report sprint 2.8
**Cohort discovery**
- ‘Creating a Cohort’, instead of 'Creating Cohorts' title grammar.
- Random 'w' at end of address in Cohort Discovery T&Cs
- 'Form' typo in section header change to 'from'

Exit report - 2.8 modifications

---

src/pages/DataAccessRequest/DataAccessRequest.js

[IG-1415](https://hdruk.atlassian.net/browse/IG-1415)
The fix is about reversing the order of the modals when a user submits an application.
With this fix the modal about missing fields is shown before the confirmation modal and not after.

Fix for IG-1415 reverse order of the modals

---

src/pages/DataAccessRequest/DataAccessRequest.scss
src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js
src/pages/DataAccessRequest/components/TypeaheadDataset/TypeaheadDataset.js

Update dataset typeahead to support multiple publishers when no publisher is set.  This needs to be configurable by a property, so that the DAR application form is not affected as it should only ever render datasets for one publisher.
- Updated dataset typeahead
- Updated DAR application form instance of typeahead to use only single custodian
- Made css classes generic to reflect changes in typeahead options output (can be either dataset description or publisher name now)

IG-1442 - Update dataset typeahead to support multiple publishers

---

src/pages/commonComponents/searchBar/SearchBar.js

[SUPP-443](https://hdruk.atlassian.net/browse/SUPP-443?atlOrigin=eyJpIjoiNmY1NGVlMTNiZTU4NDZkYzhmZmNlYmZlZGQ1YjUyZjciLCJwIjoiaiJ9)
[As reported](https://hdruk.atlassian.net/browse/SUPP-443?atlOrigin=eyJpIjoiNmY1NGVlMTNiZTU4NDZkYzhmZmNlYmZlZGQ1YjUyZjciLCJwIjoiaiJ9), the custodian could get around starting a review by clicking upon the notification. This meant when they requested feedback it did not go back to the applicant due to missing "Start Review" phase of the process which is supposed to be activated in the dashboard.
We now redirect to the Publishers dashboard where they can start the review process.

SUPP-443 DAR redirect application on receive 

---

src/pages/dataset/DatasetPage.js

On linked datasets we are showing a dataset link only if MDC input data matches a **URL link** to a dataset on the gateway.  This logic is incorrect.  We should be showing the dataset link if MDC input data matches a **Dataset title** instead.
This change involves calling a new endpoint to check if a dataset exists in our database based on a given dataset title.
Logic from ticket:
"On linked datasets, we have a bit of code to identify the input from the user.
How it works today:
1. URL + matches Gateway dataset = show dataset link
2. URL + does not match Gateway dataset = show external linK
3. String of text = show unrecognised dataset label + link to search
How it should be:
1. Dataset title + matches Gateway dataset = show dataset link
2. URL = show external link (any URL, gateway or …

Linked datasets should match on title not URL

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js
src/pages/DataAccessRequest/components/DuplicateApplicationModal/DuplicateApplicationModal.js

Fixed a state issue relating to the reload of the application page once a clone operation had completed.  Previously, the dataset selector was being disabled when the page loaded the newly created application.
**Development** 
- Added a key prop to be passed down through component tree to ensure all child component re-render (DAR -> About application -> Dataset selector)
- Fixed spelling mistake

DAR - Cloning - Fixed locking dataset selector and spelling mistakes

---

src/pages/dataset/DatasetPage.js

On linked datasets we are showing a dataset link only if MDC input data matches a URL link to a dataset on the gateway. This logic is incorrect. We should be showing the dataset link if MDC input data matches a Dataset title instead.
This change involves calling a new endpoint to check if a dataset exists in our database based on a given dataset title.
Logic from ticket:
"On linked datasets, we have a bit of code to identify the input from the user.
How it works today:
1. URL + matches Gateway dataset = show dataset link
2. URL + does not match Gateway dataset = show external linK
3. String of text = show unrecognised dataset label + link to search
How it should be:
1. Dataset title + matches Gateway dataset = show dataset link
2. URL = show external link (any URL, gateway or not)
3. …

Linked datasets should match title not url

---

src/index.js

- Added react app version to Sentry initialisation, value must be added in Cloud run for injection at build time.

Sentry - release versioning

---

src/css/styles.scss
src/pages/dashboard/Account.js
src/pages/dashboard/AccountMembers.js
src/pages/dashboard/AccountTeamManagement.js

IG-1413
Moved members into team management as per design from zeplin. Picked up on 08/04/2021 pr meeting. Rectified to suit the designs.
Other changes include 
- SCSS flex properties
- Callback for Team management tab change to hide action bar if on members tab
- Update of HTML and remove empty class tags

IG-1413 - Moved members tab into team notifications

---

src/pages/DataAccessRequest/DataAccessRequest.js

Data Access Request (DAR) applications attributed to NCS projects are linked via the ID field of the project entity.  This is stored in the 'aboutApplication' object in the DAR.  The property which stores the ID itself does not have database or ODM validation, which allowed the saving of a double type representation of the selected project ID.  The value should always be captured as a string however.
- Added explicit cast to project Id field to ensure format is always string

SUPP-460 - DAR - National Core Studies Project Id Data Format Fix

---

src/pages/search/SearchPage.js

Fix broken search filter during selection
If you select a publisher and try deselect using the provided checkbox you will realise you can not deselect it. The following update allows you to uncheck the value, this was due to another fix that had conflicted with the logic, additional logic has been put in which is correct and tested.

SUPP - Fixed broken filters check/uncheck

---

src/pages/commonComponents/CommonComponents.scss
src/pages/commonComponents/RemoveUploaderErrorModal.js
src/pages/commonComponents/RemoveUploaderModal.js
src/pages/commonComponents/RemoveUploaderModal.scss
src/pages/commonComponents/Uploader.js
src/pages/paper/AddEditPaperForm.js
src/pages/paper/PaperPage.js
src/pages/project/AddEditProjectForm.js
src/pages/project/ProjectPage.js
src/pages/tool/AddEditToolForm.js
src/pages/tool/ToolPage.js

Users can now add authors who are not registered on the Gateway to a tool/project/paper.
Only people listed as Uploaders (stored in authors in B/E) will have edit rights on an entity.
**Authors** will be stored as a String in the backend in a new field called **_authorsNew_**.
**Uploaders** will remain stored in the **_authors_** field as an array of numbers.
The original uploader will remain stored in the Number field **_uploader_**.
Any uploaders who had previously not listed themselves as authors will not lose edit privileges as there was a data fix to add those uploaders into the authors array for these cases.  See [IG-1961](https://hdruk.atlassian.net/browse/IG-1961) 
See [IG-1766](https://hdruk.atlassian.net/browse/IG-1766) for implementation rationale.

Distinguishing author/uploader for tools/projects/papers

---

src/pages/commonComponents/relatedObject/RelatedObject.js

[IG-2090](https://hdruk.atlassian.net/browse/IG-2090)
Removing previous formatting that was putting authors in bulleted list
Added turnery expression to make sure the last author doesn't have a comma put after it

IG-2090 - Names of authors on search results are stacking instead of appearing in one line

---

src/pages/commonComponents/userMessages/UserMessages.scss
src/pages/dataset/components/DatasetAboutCard.js

**Issues**
There is a display issue with the message drawer when attempting to contact a custodian with a long name while using a regular/small resolution size. This causes the message form to be unusable in some cases, with inputs appearing outside the viewport.
There are two buttons on the dataset page which should link to an application form/opportunity to message the custodian. Only one button was updated to reflect the make an enquiry user flow change we previously.
Removed CSS on header containing custodian name which was preventing the element from wrapping and not working as expected with ellipsis (should have truncated the text)
Updated user flow to match designs and existing 'How to request access' button

SUPP-598 + SUPP-599 (Display issue on DAR first message and user flow fixes)

---

src/utils/DarValidation.util.js

**Issue**
Rare problem occurring for some users where an attempt to submit a totally empty application form throws a javascript error in the console instead of performing validation and redirecting the user to the next validation error. 
1. Added default empty object values to questionAnswers parameter before passing to Winterfell library for validation.

IG-2155 - DAR - Application submit button error when no answers set

---

src/pages/paper/PaperPage.js

**Issue**
Search function not firing from search bar when the user is in the paper page.
**Fix**
Bug found where a reference to previous class based component existed, which needed updated to React hook state for the searchString parameter. A javascript exception was occurring because 'this.state' does not exist in a functional component.

SUPP-603 - Search failing on paper page

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/Messages/Messages.js
src/pages/DataAccessRequest/components/QuestionActionTabs.js

**Problem**
Share application modal is showing when a custodian member tries to start a conversation on an application.  This should only be appearing for the applicant when they want to start a conversation before submission.  Once submitted, the custodian can view the application and it therefore does not need to be shared.
- Passed application status into messaging component to determine when to correctly show the 'share application' modal.  This should only be visible when the application is in presubmission and is not visible to the custodian.  It should never show for the custodian either, so in the case that the application has not be shared but it is submitted, the new IF clause will still avoid showing the modal.
- Updated IF statement that conditionally shows the …

SUPP-632 - Contextual messaging fixed share application flow

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/Messages/Messages.js
src/pages/DataAccessRequest/components/QuestionActionTabs.js

**Problem**
Share application modal is showing when a custodian member tries to start a conversation on an application. This should only be appearing for the applicant when they want to start a conversation before submission. Once submitted, the custodian can view the application and it therefore does not need to be shared.
- Passed application status into messaging component to determine when to correctly show the 'share application' modal. This should only be visible when the application is in presubmission and is not visible to the custodian. It should never show for the custodian either, so in the case that the application has not be shared but it is submitted, the new IF clause will still avoid showing the modal.
- Updated IF statement that conditionally shows the …

SUPP-632 - Contextual messaging fixed share application flow - UAT

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/Messages/Messages.js
src/pages/DataAccessRequest/components/QuestionActionTabs.js

**Problem**
Share application modal is showing when a custodian member tries to start a conversation on an application. This should only be appearing for the applicant when they want to start a conversation before submission. Once submitted, the custodian can view the application and it therefore does not need to be shared.
- Passed application status into messaging component to determine when to correctly show the 'share application' modal. This should only be visible when the application is in presubmission and is not visible to the custodian. It should never show for the custodian either, so in the case that the application has not be shared but it is submitted, the new IF clause will still avoid showing the modal.
- Updated IF statement that conditionally shows the …

SUPP-632 - Contextual messaging fixed share application flow - hotfix

---

src/pages/commonComponents/AdvancedSearchModal/AdvancedSearchModal.js

As the login model overlaps the advanced search modal, I set enforced focus to false

Disable enforce focus

---

src/pages/DataAccessRequest/components/TypeaheadDataset/TypeaheadDataset.js
src/pages/commonComponents/userMessages/components/EnquiryMessage.js

**Issue reported by user**
'I tried to select multiple datasets in a first message. When I do this for CPRD, no additional datasets come up in addition to the one pre-selected. When I do this for NHSD, only few datasets come up (but there should be many more). When I do this for SAIL datasets, all relevant datasets come up and I can add more than one (which is good).'
**Investigation**
This issue was caused by the reuse of the dataset typeahead used in the 5 safes application form which was filtering out non 5 safes datasets.
- Added typeahead configuration prop to allow the inclusion or exclusion of non 5 safe datasets

SUPP-643 - DAR - Fixed First Message not including non 5 safes datasets

---

src/pages/DataAccessRequest/components/Uploads/Uploads.js

**Issue**
Data access request file upload not working due to failing validation logic.  Issue was caused by an LGTM correction that changed the output of the parameter used for validation.
- Corrected regression issue in file description extract as shown in files changed.

SUPP-649 - File upload validation failure

---

src/pages/DataAccessRequest/DataAccessRequest.js

**Description**
When submitting an access request which has requested updates returned to the applicant, if the applicant used the revert answer functionality then submitted the application with the answer blank, an error was thrown when loading the application again.
The fix was to prevent the submit button being available unless all requested updates have been completed.
- Updated showSubmit logic which controls appearance of the submit updates button to only show when the applicant has completed all requested updates.

SUPP - DAR: Fixed issue where applicant could submit incomplete requested updates causing error on next load

---

cloudbuild_uat.yaml

Update to the UAT cloudbuild yaml to increase the timeout for the build

Update to the UAT cloudbuild yaml to increase the timeout for the build

---

src/pages/search/SearchPage.js

release-fix/gat 676 - Calling wrong method to set reset all filters at top level

release-fix/gat 676 - Calling wrong method to set reset all filters at top level

---

src/pages/search/components/FilterTree/FilterTree.js

release-fix/GAT-681 - child filters not highlighting in spatial filters

release-fix/GAT-681 - child filters not highlighting in spatial filters

---

src/components/CheckboxTree/CheckboxTree.styles.js
src/pages/search/components/Filter.js
src/pages/search/components/FilterTree/FilterTree.js

Disable the clicking of greyed-out filters, both for the "normal" filters and the checkbox tree for the spatial filters.

story/GAT-917 - disable clicking of greyed-out filters

---

package-lock.json
package.json
src/configs/url.config.js
src/modules/RelatedResourcesTab/RelatedResourcesTab.components.jsx
src/modules/RelatedResourcesTab/RelatedResourcesTab.jsx
src/modules/RelatedResourcesTab/RelatedResourcesTab.test.js
src/modules/RelatedResourcesTab/RelatedResourcesTab.utils.jsx
src/modules/RelatedResourcesTab/index.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/dataset/DatasetPage.js
src/services/mockServer.js
test/handlers/index.js
test/handlers/relatedResources/v1/data.js
test/handlers/relatedResources/v1/handlers.js
test/handlers/relatedResources/v1/index.js
test/mocks/generateData.js

- Removed related resource logic from DataSetPage and put in its own module 
- Introduced 'faker' to generate mock data for unit tests
- Created handler functions to mock `relatedobject` api
- Fixed count issue in GAT-1768
- Fixed multiple api calls issue in GAT-1769

GAT-1769/GAT-1768: Refactoring related resources tab
