HDRUK/gateway-web

src/pages/dashboard/DataAccessRequests/DataAccessRequests.scss

Word break

---

src/pages/commonComponents/userMessages/UserMessages.scss
src/pages/commonComponents/userMessages/components/MessageHeader.js

Update from Monique observation on messages. Message button for 'Show Applications' is now a link.

Update for ticket IG-669 monique

---

src/pages/DataAccessRequest/DataAccessRequest.js

Changed 'invite collaborators' to 'invite contributors' in the DAR about application section for consistency.

Fixed collaborators to contributors

---

src/pages/dashboard/Workflows/WorkflowStep.js

Fix spelling mistake with deadline

IG-757 deadline

---

src/pages/DataAccessRequest/components/TypeaheadUser/TypeaheadMultiUser.js

Missing class in typeahead needed for demo and application.

IG-CSS-MissingClass

---

src/pages/collections/CollectionPage.js
src/pages/dashboard/TeamHelp/TeamHelp.js

Fixed how closed flag is added to Help array

Ig 768 fix

---

src/pages/commonComponents/actionbar/ActionBar.js
src/pages/commonComponents/addToCollection/AddToCollection.js
src/pages/commonComponents/addToCollection/AddToCollection.scss
src/pages/dataset/DatasetPage.js

Oxford metadata catalogue link was missing from the gateway
Re-add the button to the catalogue, making the button available regardless if the user is logged in or not.

IG-706-Oxford-metadata-catalogue-link

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/dashboard/Account.js
src/pages/dashboard/Dashboard.scss
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js

- Fixed 'In review' output of application status to correctly show 'In review' instead of 'inReview' when viewing a DAR in that state
- Added chevron to team/user dropdown in account area
- Removed the local storage variable when user navigates away from account area so the menu bar navigation now links the user into the account section with themselves selected in the team menu
- Removed redundant/repeated users and roles nav item from account menu
- Removed submitted tab from DAR console for reviewers

Fix for various display issues

---

src/pages/commonComponents/actionbar/ActionBar.js
src/pages/commonComponents/actionbar/ActionBar.scss
src/pages/commonComponents/addToCollection/AddToCollection.js
src/pages/commonComponents/resourcePageButtons/ResourcePageButtons.js
src/pages/dataset/DatasetPage.js

Action bar should finish above the footer
Fixed the action bar to stop above the footer
Fixed the 'Technical Details' button to only show on datasets.

IG-720-Action-Bar

---

src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js
src/pages/DataAccessRequest/components/Uploads/AllFiles.js
src/pages/DataAccessRequest/components/Uploads/Uploads.js

Removed trim from projectName breaking if not defined

---

src/pages/DataAccessRequest/DataAccessRequest.scss
src/pages/collections/AddCollectionPage.js
src/pages/collections/EditCollectionPage.js
src/pages/dashboard/Account.js
src/pages/dashboard/AccountAdvancedSearch.js
src/pages/dashboard/AccountDatasets.js
src/pages/paper/AddEditPaperForm.js
src/pages/paper/AddEditPaperPage.js
src/pages/project/AddEditProjectForm.js
src/pages/project/AddEditProjectPage.js
src/pages/tool/AddEditToolForm.js
src/pages/tool/AddEditToolPage.js

Address issues raised by Susheel regarding the action bar.

IG-720-fixes

---

src/pages/commonComponents/CommonComponents.scss

I want to to check how this loads in beta before updating in a branch off master

SUPP-246 footer height change

---

src/pages/collections/EditCollectionPage.js
src/pages/commonComponents/CommonComponents.scss
src/pages/commonComponents/LoginModal.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/searchBar/SearchBar.scss

- Fixed ability to edit collections containing courses
- Fixed position of login modal

SUPP-261 and SUPP-248

---

src/pages/dataset/components/DataQuality.js
src/pages/dataset/components/DataQualityInfo.js

Updates for Dataset utility issue on live, this is a temporary solution to fixing the undefined issue reported from Sentry around the type error of undefined.

SUPP Updates for Dataset utility

---

src/pages/dataset/components/DataQuality.js
src/pages/dataset/components/DataQualityInfo.js

Import missing lodash

---

src/pages/dataset/DatasetPage.js
src/pages/dataset/components/TechnicalDetailsPage.js

- Applying fix backwards to Dev for display issue raised and patched in production

Supp render issue prev merge

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/DataAccessRequest.scss
src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js

1. Fixed ordering of about application steps
2. Fixed 'how to request access' button in step 4 of about application
3. Updated h3 size for DAR form

Fixed about application defects in DAR form

---

package.json

Updates to package.json recommended by synk

Updates to package.json recommended by synk

---

src/css/styles.scss
src/pages/dashboard/YourAccount.js
src/pages/registration/CompleteRegistration.js

Issue - React-Bootstrap Dropdown not working on Safari
Solution - Replace it with a Typehead

SUPP-290 & SUPP-272

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/DatePickerCustom/DatepickerCustom.js

Dev changes needed for Hotfix on 14th December 
- Change to DatepickerCustom component, date to underlying validation library now using Winterfell custom customDate in  DataAccessRequest.js
- Change to DataAccessRequest component, new Winterfell validation type for handling dates.

Changes for Dev branch based on HF Monday Dec

---

src/HDRRouter.js
src/pages/collections/EditCollectionPage.js
src/pages/commonComponents/GuardedRoute.js
src/pages/commonComponents/LoginModal.js
src/pages/course/AddEditCoursePage.js
src/pages/paper/AddEditPaperPage.js
src/pages/project/AddEditProjectForm.js
src/pages/project/AddEditProjectPage.js
src/pages/tool/AddEditToolPage.js
src/utils/GeneralHelper.util.js
src/utils/__tests__/GeneralHelper.test.js

Refactoring and updates to main routing around authorisation
Proactive code refactoring of routing regarding authorisation, a new **GuardRoute** now manages the authorisation for each route that needs an auth pattern, **isEdit** is done in the relevant components and not passed as a prop, the route can dynamically compute on the window.location.path 
A new **util** has been created **GeneralUtil** and uses named exports, this can be used for general utility functions moving forward.

Refactoring - Update to Routing within application, reduced code blueprint 

---

src/pages/dashboard/AccountCourses.js
src/pages/dashboard/AccountPapers.js
src/pages/dashboard/AccountProjects.js
src/pages/dashboard/AccountTools.js

Removed key and active from previous and next pagination to resolve issue on uat beta

IG-1017 Removed key and active from previous and next pagination

---

src/pages/dashboard/AccountCollections.js
src/pages/dashboard/AccountCourses.js
src/pages/dashboard/AccountPapers.js
src/pages/dashboard/AccountProjects.js
src/pages/dashboard/AccountTools.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js
src/pages/dashboard/Workflows/AddEditWorkflow.js

[IG-1133](https://hdruk.atlassian.net/browse/IG-1133)
Changed "Updated" to "Last activity" on Dashboard > Tools, Projects, Papers, Collections and Courses pages
Corrected typo in "average time from submission to decision" on the DAR dashboard
Removed "To add members to your team email members@HDRUK.org." from create a workflow

IG-1133 - Tidy: Various text updates

---

src/pages/dashboard/AccountAnalyticsDashboard.js
src/pages/publicDashboard/PublicAnalyticsDashboard.js

**PR**
[IG-1105](https://hdruk.atlassian.net/browse/IG-1105)
- Cards added to display when there are no results for top searches and unmet demand
- getDatesForDropdown updated to increment by month rather than day
- getDatesForDropdown updated to set time to midnight when GMT (previously set at 1am)

IG-1105 No results cards added, getDatesForDropdown updated to account for dst

---

public/index.html

[IG-1214](https://hdruk.atlassian.net/browse/IG-1214)
This includes a chunk of code placed within `index.html` that allows tracking of which external links that users click on within the gateway. 
This same chunk of code will be placed within the header code within the CMS to match the environment that the React code is in.

Track outbound links from the gateway

---

src/pages/commonComponents/CommonComponents.scss
src/pages/commonComponents/Creators.js
src/pages/commonComponents/actionbar/ActionBar.scss

[IG-434](https://hdruk.atlassian.net/browse/IG-434)
Cleanup to the authors card on Papers pages. Code changes are mainly just tweaks to margins and padding to ensure they are more aligned with the designs. 
**Desktop view**
**Mobile view**

IG-434 - Tidy: entities: authors

---

src/HDRRouter.js

Routing Update
There were guarded routes for projects, tools, papers and collections. Users who were not registered with the gateway could not access these basic routes. A change back to Reacts normal router will prevent this.

Routing update, non registered users can view tools,papers,collection

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/CustodianActionButtons/CustodianActionButtons.js
src/pages/commonComponents/searchBar/SearchBar.js
src/utils/DarHelper.util.js

[IG-972](https://hdruk.atlassian.net/browse/IG-972?atlOrigin=eyJpIjoiMTgxNDhiYzI0NzdkNGZjYThjYzE1NGE2OTVmODFkMTEiLCJwIjoiaiJ9)
New notification type added to search bar for notification workflow, code was duplicated for the notification. This is a perfect candidate for refactoring and creating a new component for notifications. 
Small fix in data access requests with assigning workflows, when trying to assign a workflow through the UI it failed. This was due to the custodian buttons passing in  an event object and not the new string value, a re-test resulted in this working.

IG-972 Add new messages/ emails as highlighted on Robin's page

---

src/css/_variables.scss
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/uatBanner/UatBanner.js
src/pages/commonComponents/uatBanner/UatBanner.scss

**PR**
[IG-1069](https://hdruk.atlassian.net/browse/IG-1069)
UAT banner added in CMS:
UAT banner React:
UAT banner React mobile:

IG-1069 UAT banner added

---

src/pages/dataset/DatasetPage.js

Details -> Standard needed to be linkified. Also the Regex that deteceted links wasn't as robust as I would like so made some alterations to it to make sure it works as intended within the description.

Making link regex more robust and adding link to Details -> Standard

---

src/css/styles.scss
src/pages/DataAccessRequest/components/DatePickerCustom/DatepickerCustom.js

[IG-1319](https://hdruk.atlassian.net/browse/IG-1319?atlOrigin=eyJpIjoiOWQ1ZDYyOTAwMzY3NGEzMjgwOTJjY2I0ZjRiNWU2MmUiLCJwIjoiaiJ9)
Yokow reported the datepicker was crashing when typing in a manual date and erasing. The issue was due to the format of dates and checking incorrectly. A fix for checking is null and only formatting when relevant fixes this.

IG-1319 Datepicker crashing update

---

src/pages/paper/PaperPage.js

IG-1339 - removing lone x from code - HF

IG-1339 - removing lone x from code - HF

---

src/pages/dashboard/AccountAdvancedSearch.js

Caroline provided some text updates for the Advanced Search page

Text updates for Advanced Search page

---

src/pages/dashboard/AdvancedSearchRequestAccessModal.js

Prepopulating text boxes for advanced search support desk ticket request

---

src/pages/DataAccessRequest/DataAccessRequest.js

Added a button in the DAR page to send an email with the DAR info.
The button is enabled only if the DAR is in progress.

New button to send DAR info by email

---

src/css/styles.scss
src/pages/collections/CollectionPage.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/course/CoursePage.js
src/pages/paper/PaperPage.js
src/pages/project/ProjectPage.js
src/pages/tool/ToolPage.js

[SUPP-419](https://hdruk.atlassian.net/browse/SUPP-419)
Merge of SUPP-419 for master release from ticket [SUPP-419](https://hdruk.atlassian.net/browse/SUPP-419).

Hotfix master supp-419

---

src/pages/DataAccessRequest/components/Uploads/Uploads.js

This pull request addresses a problem detected in file upload, where an infinite number of status checks were being performed while a web page was left open.  The case of a lack of update to uploaded files will be limited now to 5 minutes of periodic checks.
**Changes**
- Added in a maximum number of 30 retries over a period of 5 minutes

DAR - File upload fix for infinite status checks

---

src/pages/dashboard/TopDatasets.js

- Removed redundant state from top datasets display component
- Updated dataset links to use PIDs
- Updated data references to match backend changes

IG-1346 - Updated top datasets dashboard display

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/components/ApplicantActionButtons/ApplicantActionButtons.js
src/pages/DataAccessRequest/components/ConfirmSubmissionModal/ConfirmSubmissionModal.js
src/pages/DataAccessRequest/components/ConfirmSubmissionModal/ConfirmSubmissionModal.scss

[IG-1415](https://hdruk.atlassian.net/browse/IG-1415)
Added a new modal to make the user confirm before submitting (or resubmitting) an application

IG-1415 Add new modal to confirm application submission

---

src/pages/collections/AddEditCollectionForm.js
src/pages/collections/CollectionPage.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/commonComponents/relatedResourcesModal/RelatedResourceModal.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/searchBar/SimpleSearchBar.js
src/pages/dashboard/AccountCollections.js

Test ids added for Collections E2E test.
For test see: https://github.com/HDRUK/gateway-e2e/pull/4

Test ids added for Collections E2E test

---

src/pages/dashboard/AccountAdvancedSearch.js

Uncommented redirect for rquest production instance

Uncommented redirect for rquest production instance

---

src/pages/dashboard/AccountAdvancedSearch.js

Revert "Uncommented redirect for rquest production instance"

---

src/pages/DataAccessRequest/DataAccessRequest.js

Remove double quotes from modal

remove double quotes from modal

---

src/pages/dashboard/AccountCollections.js

[IG-1321](https://hdruk.atlassian.net/browse/IG-1321)
- Pagination added to collections dashboard
- Archive, unarchive and delete updated to ensure they reload on correct tab and page following action

IG-1321 Pagination added to collections dashboard

---

src/pages/DataAccessRequest/DataAccessRequest.js

Changes:
‘Email application' --> 'Email me a copy'
‘…to the email address provided in your HDR UK account.’ --> '……to …to the email address provided in your HDR UK account where it will be available for you to print.”

Change text in button and modal for draft application 

---

src/pages/collections/AddEditCollectionForm.js

[IG-1325](https://hdruk.atlassian.net/browse/IG-1325)
Additional value passed in add/edit collection form

IG-1325 Additional value passed in add/edit collection form

---

src/pages/search/SearchPage.js

# PR
Update Search mapper for entities
Collections do not render on uatbeta, a fix to the mapper from collections to collection resolves this issue. Remove collection sort, should not show as per IG-1243

DEV - Update collection mapper

---

src/css/styles.scss
src/pages/search/SearchPage.js

IG-1372 fix for collections to collection. Removal of Collection sort and additional anchor style to address issues with links breaking parent containers

UATBeta Fix IG-1372

---

src/css/styles.scss

Fix all anchors that spill over  parent containers to break by word, fixes all entity issues reported by Yokow.

SUPP - Overflow fix

---

src/pages/commonComponents/userMessages/UserMessages.scss

IE Fixes for messaging
A PR to fix the fundamental functionality of the messaging panel, this will allow users from an IE instance to message custodians were previously they have not been able to.

IG-1172 IE Fixes

---

src/pages/collections/AddEditCollectionPage.js
src/pages/course/AddEditCoursePage.js
src/pages/paper/AddEditPaperPage.js
src/pages/project/AddEditProjectPage.js
src/pages/tool/AddEditToolPage.js

Update to remove related resource code to include a check for pid

IG-1635 - Update to remove related resource code to include a check for pid

---

src/pages/DataAccessRequest/DataAccessRequest.js

[IG-1630](https://hdruk.atlassian.net/browse/IG-1630)

Updated API call to use multiple tags

---

package-lock.json
package.json
src/HDRRouter.js
src/pages/commonComponents/FieldRepeater/Field.js
src/pages/commonComponents/FieldRepeater/FieldRepeater.js
src/pages/commonComponents/FieldRepeater/FieldRepeater.scss
src/pages/commonComponents/FieldRepeater/FieldRepeaterAction.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/dashboard/Account.js
src/pages/dashboard/AccountMembers.js
src/pages/dashboard/AccountTeamManagement.js
src/pages/dashboard/Dashboard.scss
src/pages/dashboard/Team/TeamEmailAlertModal.js
src/pages/dashboard/Team/TeamEmailAlertModal.scss
src/pages/dashboard/Team/TeamGatewayEmail.js
src/pages/dashboard/Team/TeamGatewayNotificationEmails.js
src/pages/dashboard/Team/teamUtil.js

[IG-1413](https://hdruk.atlassian.net/browse/IG-1413) Create UI to capture additional email address within team area, part of epic [IG-1557](https://hdruk.atlassian.net/browse/IG-1557)
This PR covers the UI for team management and team notifications. A manager can now add team email address and remove accordinly.
- User turn on / off email notifications to their gateway email address.
- Admins can configure team notifications current DAR notifications on / off.
- Validation that one option must be selected

IG-1413 Team Management Notifications

---

src/pages/search/Search.scss

[IG-1699](https://hdruk.atlassian.net/browse/IG-1699) Filters improvement for list of filters selected
Yokow picked up on an improvement to filters, when the filters selected exceeds more than 6 it can be rather lengthy and pushes the design down the page. Yokow and the ds team along with Susheel have suggested the change which enhances the overall user experience.
Attached screenshot of improvement
- Update to search.scss

IG-1699 - Filter improvement for search filters applied 

---

src/css/styles.scss

[IG-1696](https://hdruk.atlassian.net/browse/IG-1696)

IG-1696 remove fixed size from pagination list item

---

src/pages/dashboard/AccountMembers.js
src/pages/dashboard/AccountTeamManagement.js
src/pages/dashboard/Team/TeamEmailAlertModal.js
src/pages/dashboard/Team/TeamGatewayEmail.js

# PR
IG-1413 linked to members and iteration of roles
Found an issue with members and a member having multiple roles. When a user had more than one role we were not presenting this as we were only taking the first value in the array and showing it. The code has been updated to map over the roles value and output according roles length.

IG-1413 Members roles repeat out, fixed issue for user who has multiple roles

---

src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/commonComponents/relatedObject/RelatedObject.scss

[IG-1674](https://hdruk.atlassian.net/browse/IG-1674)

IG-1674 publisher name on dataset displays an underline on hover

---

src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/commonComponents/relatedObject/RelatedObject.scss

[IG-1675](https://hdruk.atlassian.net/browse/IG-1675)

IG-1675 Courses card view added underline on hover and filtering

---

src/css/styles.scss

[IG-1696](https://hdruk.atlassian.net/browse/IG-1696)

Remove fixed page Item width

---

public/index.html

[IG-1726](https://hdruk.atlassian.net/browse/IG-1726)

IG-1726 Changed gateway title

---

src/pages/search/SearchPage.js

[IG-1655](https://hdruk.atlassian.net/browse/IG-1655)
Lines 138-139
Added logic to expand the chat window if a param is present in the URL

IG - 1655 Notification dropdown and chat window

---

src/pages/search/SearchPage.js

[IG-1680](https://hdruk.atlassian.net/browse/IG-1680)

IG-1680 Added sort by latest option for People

---

src/pages/commonComponents/CommonComponents.scss

The color of the buttons in the footer was green on hover.
It needs to be white instead.

Footer buttons white color on hover

---

src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js

Update for UATBeta on button position, resolves placement issue reported by Robin. Using bootstrap classes to control the position of it.

DAR About application update for button position

---

src/pages/search/SearchPage.js

[IG-1677](https://hdruk.atlassian.net/browse/IG-1677)
- Addition of 2 new sorts for datasets: latest and related resources
- Update default sort for datasets to be metadata quality if there is no search term and to match search term when there is one

IG-1677 latest and related resources sorts added for datasets

---

src/pages/commonComponents/resourcePageButtons/ResourcePageButtons.js
src/pages/course/AddEditCourseForm.js
src/pages/course/CoursePage.js
src/pages/dashboard/AccountCourses.js

See https://github.com/HDRUK/gateway-e2e/pull/9 for details

Added some test ids for courses and editing a resource

---

src/pages/collections/CollectionPage.js

IG-1808
IG-1808 displays a count for the total number of times a collection has been viewed.

IG-1808 Count for collection view

---

src/pages/collections/CollectionPage.js
src/pages/collections/Collections.scss
src/pages/collections/CollectionsSearch.js
src/pages/search/Search.scss

[IG-1740](https://hdruk.atlassian.net/browse/IG-1740)
Added skeletons for search bad and sorting for collections page

IG-1740 F/E Search and sort UI - 2pt 

---

src/pages/search/Search.scss
src/pages/search/components/Filter.js

IG-1661
Filter scss for the display of any beta filters, a small change to support Beta filters. Will be as per design teal with white colour.

IG-1661 Commercial usage Beta Filter label

---

src/pages/collections/CollectionPage.js
src/pages/collections/Collections.scss
src/pages/collections/CollectionsSearch.js
src/pages/search/components/SortDropdown.js

[IG-1741](https://hdruk.atlassian.net/browse/IG-1741)
[IG-1742](https://hdruk.atlassian.net/browse/IG-1742)
[IG-1744](https://hdruk.atlassian.net/browse/IG-1744)
Adding search logic to search bar on the collections page
Search functionality will search through both the resource's name, description and tags and will return it if there is a positive result. 
Added pagination that will dynamically show the top 24 items 
Adding sort logic to collections page 
Metadata quality sort unique to datasets

IG-1744 - Searching and sorting logic for searching within collections

---

src/pages/dataset/Dataset.scss
src/pages/dataset/DatasetPage.js
src/pages/dataset/DatasetSchema.js
src/pages/dataset/components/DatasetAboutCard.js

SUPP-526 - V2 description not showing for new dataset versions

IG-1937 - Adding in missing observation fields to the data page

---

src/pages/commonComponents/userMessages/UserMessages.scss

IE 11 updates for first messaging
Update for IE 11 fixes constrained width and enables the user to scroll down if needed.
Before
After

SUPP-IE11 - Styling update IE11 Browser Stack

---

src/pages/commonComponents/searchBar/SearchBar.scss
src/pages/search/Search.scss
src/pages/search/components/SortDropdown.js

Highlighted items are not selectable unless you click directly on the text
On Safari inside react app, the display of the notifications bell icon breaks when the notifications tray is open.

IG-1974 - Redesign tidy ticket

---

src/pages/commonComponents/userMessages/UserMessages.js

[IG-2022](https://hdruk.atlassian.net/browse/IG-2022)

IG-2022 feature switch - first message

---

src/pages/commonComponents/searchBar/SearchBar.scss

Was already done in dev as part of another ticket

Removing notification bell background.

---

src/pages/commonComponents/Footer.js
src/pages/commonComponents/dataSetModal/DataSetModal.js
src/pages/dataset/DatasetPage.js

Commenting out code that is needed for the make an enquiry journey

Make an enquiry feature switch

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js
src/utils/DarHelper.util.js
src/utils/DatasetOnboardingHelper.util.js
src/utils/__mocks__/DarHelper.mock.js

Updates to selection of versioning to support major versions and fixes for minor versioning
- Updated versioning logic to be handled by backend
- Fixed blank output of updated answers to submit updates modal
- Updated submit application to take the applicant to in review tab if submitting updates

IG-1919 - DAR - Versioning/Amend

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js
src/utils/DarHelper.util.js

Change amend logic to create a new major version in submitted status instead of in review.
- Updated logic on frontend DAR dashboard to support submitted amendments and start review
- Added redirect function to ensure managers cannot circumvent the start review process by using the version selector to view a submitted application

DAR - Update Amend logic to start at submitted status instead of in review

---

src/pages/DataAccessRequest/components/ActivityLog/ActivityLog.js
src/pages/dashboard/Account.js
src/pages/dashboard/DataAccessRequests/AccessActivity/AccessActivity.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js

[IG-1994](https://hdruk.atlassian.net/browse/IG-1994)

Created summary page for activity log

---

src/pages/commonComponents/userMessages/UserMessages.js
src/pages/commonComponents/userMessages/components/EnquiryMessage.js

[IG-2022](https://hdruk.atlassian.net/browse/IG-2022)

IG-2022 undo first message feature switch

---

src/pages/search/SearchPage.js

Removal of extra sort dropdown introduced in merge to master before latest deployment.

IG-2081 - Fix collection additional dropdown

---

src/pages/commonComponents/dataSetModal/DataSetModal.js
src/pages/dataset/DatasetPage.js

Undoing the feature switch for Make an Enquiry so that the functionality is on dev

Uncommented out Make an Enquiry code

---

security-vulnerability-discloure-policy.md
security.txt

Adding security and vulnerability disclosure policy

---

src/pages/commonComponents/dataSetModal/DataSetModal.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/userMessages/components/EnquiryMessage.js
src/pages/commonComponents/userMessages/components/MessageItem.js
src/pages/dataset/DatasetPage.js
test/SearchBar.test.js

[IG-1929](https://hdruk.atlassian.net/browse/IG-1929)
Addition of test ids

IG-1929 Added test ids

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DataAccessRequest/DataAccessRequest.scss
src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js
src/pages/DataAccessRequest/components/AlertBox/AlertBox.js
src/pages/DataAccessRequest/components/CustodianActionButtons/CustodianActionButtons.js
src/pages/commonComponents/searchBar/CmsDropdown.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js

Completion of amend feature including highlighting of answers changing between major versions
- Added highlighting of changes to selected datasets during an amendment when viewed by the Custodian (new major application version)
- Fixed disabled token display in type ahead component which should have had a white background on the tokens
- Removed buttons from before you begin section when the contents are read only
- Updated custodian action buttons to hide make a decision if there are unanswered amendments present

DAR - Amend - IG-1921 + IG-2021

---

src/pages/commonComponents/communicateDataCustodianModal/CommunicateDataCustodianModal.js
src/pages/commonComponents/dataSetModal/DataSetModal.js
src/pages/commonComponents/dataSetModal/DataSetModal.scss
src/pages/commonComponents/userMessages/components/MessageHeader.js

Original 
https://github.com/HDRUK/gateway-web/pull/671

UATBeta PR: IG-2086 - Changes to non 5Safes modal 

---

src/pages/dashboard/AccountCollections.js
src/pages/dashboard/Dashboard.scss
src/pages/dashboard/EntityActionButton.jsx

[IG-1751](https://hdruk.atlassian.net/browse/IG-1751)
DatasetModal is smaller and displays non 5Safes text from CMS when on a non 5Safes dataset. 
Changing colour of "Submit Application" on the message header

IG-1751 - Update delete confirmation model to be more in line with the rest of the site

---

src/pages/DatasetOnboarding/DatasetOnboarding.js
src/pages/commonComponents/searchBar/SearchBar.js

[IG-2050](https://hdruk.atlassian.net/browse/IG-2050)

IG-2050 adding notification for delete draft dataset

---

src/pages/DataAccessRequest/components/DatePickerCustom/DatepickerCustom.js
src/pages/DatasetOnboarding/components/DatePickerCustom/DatepickerCustom.js
src/pages/course/AddEditCourseForm.js

[IG-2054](https://hdruk.atlassian.net/browse/IG-2054)
Added Year and Month dropdowns to datepicker to allow easy access to different times
Added custom date picker to the add/edit courses page for consistancy

IG-2054 - Added year/month options to DatePickerCustom

---

src/pages/DataAccessRequest/components/ActivityLog/ActivityLog.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js

Requirement to complete a basic integration to backend for pulling through activity log records for an application including all relevant versions.
1. Completed loose integration to back end rendering out results (to be refactored into sub-components)
2. Converted activity log component into a functional component from class based

IG-1998 - DAR - Initial Activity Log Integration

---

src/pages/commonComponents/userMessages/components/EnquiryMessage.js

[IG-2129](https://hdruk.atlassian.net/browse/IG-2129)

IG-2129 Copy changes for first message

---

src/pages/dataset/components/DatasetAboutCard.js

Revert "SUPP-588 Dataset typo fix"

---

src/pages/commonComponents/userMessages/components/EnquiryMessage.js

Revert "IG-2129 Copy changes for first message"

---

src/pages/dataset/components/DatasetAboutCard.js

Revert "Revert "SUPP-588 Dataset typo fix""

---

src/pages/commonComponents/userMessages/components/EnquiryMessage.js

Revert "Revert "IG-2129 Copy changes for first message""

---

src/pages/DataAccessRequest/components/MissingFieldsModal/MissingFieldsModal.js
src/utils/DatasetOnboardingHelper.util.js

[SUPP-593](https://hdruk.atlassian.net/browse/SUPP-593)
Changed wording on missing fields modal.

SUPP-593 - Incorrect wording in DAR submission popup

---

src/css/styles.scss
src/pages/dashboard/AccountMembers.js

ICODA-107 removed display: flex attribute from .entryBox class in styles.scss to allow technical details metadata variables to display correctly

ICODA-107 removed display: flex attribute from .entryBox

---

src/pages/commonComponents/searchBar/SearchBar.js

Added new notification type for manual events created against activity log.

IG-2002 - DAR - Activity Log - Manual Event Notification

---

src/pages/commonComponents/searchBar/UserDropdownItems.js
src/pages/commonComponents/searchBar/UserDropdownTeams.js

[IG-2107](https://hdruk.atlassian.net/browse/IG-2107)
Added teams link to user dropdown (only accesible if the user is an admin).

IG-2107 : Adding teams link to user dropdown

---

src/pages/DatasetOnboarding/formSchema.js

[IG-2177](https://hdruk.atlassian.net/browse/IG-2177)

IG-2177 Copy change

---

src/pages/commonComponents/searchBar/SearchBar.js

[IG-2109](https://hdruk.atlassian.net/browse/IG-2109)
- Notification type added for 'team added'
- Navigates to new team management on click

IG-2109 Addition of 'team added' notification type

---

src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/searchBar/SearchBar.scss

[IG-2148](https://hdruk.atlassian.net/browse/IG-2148)

IG-2148 : Fixing messages count badge position

---

src/pages/commonComponents/dataSetModal/DataSetModal.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/searchBar/SearchBar.scss
src/pages/dataset/DatasetPage.js
src/pages/dataset/components/DatasetAboutCard.js

Inconsistency was discovered in the 2 links to request access from the dataset page, which one link was requesting a logged out user to login before the first modal was shown, whereas the other was requesting a login first.
- Updated both journeys to require login before information modal appears.

IG-2203 Fix for UAT defect - Request access link journey 

---

src/css/styles.scss
src/pages/dashboard/Account.js
src/pages/dashboard/AccountTeams.js
src/pages/dashboard/Dashboard.scss
src/pages/dashboard/Team/AddEditTeamsPage.js
src/pages/dashboard/Team/TeamInfo.js

[IG-2105](https://hdruk.atlassian.net/browse/IG-2105)
Added functionality to add teams
Add placeholders for edit teams

IG-2105 - Adding teams

---

src/pages/DataAccessRequest/components/ActivityLog/ActivityLogVersionCard.js
src/pages/dashboard/DataAccessRequests/DataAccessRequests.js
src/utils/DarHelper.util.js

Activity log should display the number of days since a version was submitted along with the % time spent with applicants vs custodians.
- Updated conditional statements that output the number of days since submission/start/resubmission of application versions.

IG-2004 - DAR - Update party time distribution output for application versions

---

public/index.html

adding cookie pro banner script to index.html to enable cookie accept/reject functionality

Icodara 110

---

src/HDRRouter.js
src/pages/commonComponents/CookiePage.js
src/pages/commonComponents/CookiePage.scss
src/pages/commonComponents/Footer.js

Requires get link to be updated in CookiesPage when new cookies word press page has been made available prior to merging. Current https://icoda-research.org/icoda-gateway/ link agreed stand in to allow for development.

Icodara 109

---

src/pages/commonComponents/AboutPage.scss

Icodara 118 fix v2

---

src/pages/commonComponents/AdvancedSearchModal/AdvancedSearchModal.js
src/pages/commonComponents/AdvancedSearchModal/AdvancedSearchModal.scss
src/pages/commonComponents/DataUtilityWizard/DataUtilityWizard.scss
src/pages/commonComponents/DataUtilityWizard/DataUtilityWizardModal.js
src/pages/search/SearchPage.js

[IG-2169](https://hdruk.atlassian.net/browse/IG-2169)
Basic data utility wizard functionality created
- Filters being set from wizard
- Steps work as intended
- Can search from wizard
- Displays number of results dynamically
- Clearing filters when changing from one selection to another in the wizard
- Each entry needs the "value" property to be passed through to the front end. Each entry currently has "impliedValues" but that isn't quite what we need to get the filters working properly from the wizard. Line 211 in SearchPage.js is what will give us what we need when each node has a "value" property being passed through to it.

IG-2169 - Data Utility Wizard

---

src/pages/DataAccessRequest/components/TypeaheadUser/TypeaheadMultiUser.js
src/pages/DatasetOnboarding/DatasetOnboarding.js
src/pages/DatasetOnboarding/components/MultiField/MultiField.js
src/pages/DatasetOnboarding/components/MultiField/TypeaheadMultiField.js
src/pages/DatasetOnboarding/components/TypeaheadUser/TypeaheadMultiUser.js
src/pages/commonComponents/BaseURL.js
src/pages/commonComponents/errorModal/ErrorModal.js
src/pages/dashboard/Account.js
src/pages/dashboard/AccountAnalyticsDashboard.js
src/pages/dataset/components/TechnicalMetadataVariables.js
src/pages/publicDashboard/PublicAnalyticsDashboard.js
src/utils/DatasetOnboardingHelper.util.js

[IG-2215](https://hdruk.atlassian.net/browse/IG-2215)

IG-2215 updated link

---

src/pages/collections/CollectionPage.js

[IG-2262](https://hdruk.atlassian.net/browse/IG-2262)
- Additional fields added to search in collections to ensure it covers all required fields for each resource type
- Sort by relevance aka match to search terms updated to sort using a count of how many times the search term appears within all the required fields
- Sort triggered each time the filteredData is updated to ensure its sorting using the updated filteredData

IG-2262 fix for collections search and sort by relevance

---

src/pages/DataAccessRequest/components/AboutApplication/AboutApplication.js

Changes requested to amend functionality copy:
[Amend - 03.09.21.pptx](https://github.com/HDRUK/gateway-web/files/7109328/Amend.-.03.09.21.pptx)
Comments from client:
- Any in-line change to a question should be flagged with the wording: Applicant has requested this as an amendment to the approved application on XX date.
- It could read applicant has submitted an amendment request to an approved application (to indicate at this stage it is still only a request and needs to be approved before it becomes an amendment).
- In the first in app notification it could just read “your amendment request was successfully submitted” (i.e., remove ‘with updates’). If anything it should refer to what the approved application reference is.
- Same for custodian view – “An amendment request has been …

DAR - Amend - Copy changes

---

src/pages/commonComponents/searchBar/UserDropdownItems.js
src/pages/dashboard/Account.js
src/pages/dashboard/AccountCohorts.js

[IG-2238](https://hdruk.atlassian.net/browse/IG-2238)
- Link to Cohorts dashboard added to user nav menu and dashboard tabs

IG-2238 Cohort Dashboard added to account tabs and user nav dropdown

---

package.json

Updating package.json to include GTM module.

Add NPM for Google Tag Manager

---

src/pages/DataAccessRequest/DataAccessRequest.js
src/pages/DatasetOnboarding/DatasetOnboarding.js
src/pages/DatasetOnboarding/components/ApplicantActionButtons/ApplicantActionButtons.js
src/pages/DatasetOnboarding/components/CustodianActionButtons/CustodianActionButtons.js
src/pages/commonComponents/ActionBarMenu/ActionBarMenu.js
src/pages/commonComponents/DatasetCard.js
src/pages/commonComponents/Login.js
src/pages/commonComponents/addToCollection/AddToCollection.js
src/pages/commonComponents/searchBar/CmsDropdown.js
src/pages/commonComponents/searchBar/SearchBar.js
src/pages/commonComponents/searchBar/UserDropdownTeams.js
src/pages/commonComponents/versionSelector/VersionSelector.js
src/pages/dashboard/Account.js
src/pages/search/Filters.js

**Issue**
- Links no longer working correctly due to update to fix console errors, previously blank hrefs were updated to !# to fix empty link warnings, however this makes the page refresh in some cases.
- Changed link hrefs from !# to javascript:void(0) to prevent default link behaviour

Bug - Fixed link hrefs which were changed to avoid console errors

---

src/HDRRouter.js
src/images/icon-security.svg
src/pages/cohort/AddEditCohortForm.js
src/pages/cohort/AddEditCohortPage.js
src/pages/commonComponents/relatedObject/RelatedObject.js
src/pages/commonComponents/relatedObject/RelatedObject.scss

[IG-2182](https://hdruk.atlassian.net/browse/IG-2182)
- Initial edit cohort form built
- Validation on name and description fields
- Uploader typeahead using confirm remove modal, with minimum of 1 uploader required
- Public/private toggle - default set to public
- Lock icon for datasets with 'isLocked' true
- Datasets not shown in related resource modal

IG-2182 Edit cohort form

---

src/pages/DataAccessRequest/DataAccessRequest.js

**Issue**
Data access request functions to approve/reject/approve with conditions and update answers progressively were not functioning.
**Fix**
- Reinstated key data access request functions mistakenly commented out during LGTM fixes.  This code never made it to production.

Fix DAR functions mistakenly commented out in previous PR - UAT

---

src/pages/DataAccessRequest/components/ConfirmSubmissionModal/ConfirmSubmissionModal.js

**Issue**
DAR application submission event not being recorded correctly in Google Analytics.
**Fix**
- Incorrect ordering of firing Google Tag Manager function, page was redirected before event could fire.

Google Analytics - Fix recording of DAR application submission event

---

package.json
src/HDRRouter.js
src/css/_typography.scss
src/pages/dataUse/DataUse.scss
src/pages/dataUse/DataUsePage.js
src/pages/dataUse/SaveEditModal.js
src/pages/dataUse/edit/EditDataUse.js
src/pages/dataUse/edit/EditDataUseForm.js

[IG-2338](https://hdruk.atlassian.net/browse/IG-2338)

IG-2338 Data Use Edit UI

---

src/pages/dashboard/Components/ActivityLogCard/ActivityLogCard.jsx

All status showing rejected icon fix

Icons updated

---

src/pages/dashboard/DataAccessRequests/csvUtils.js

fixing a bug in csvUtils->extractApplicants

---

src/pages/dashboard/DataAccessRequests/csvUtils.js

Icodara 243

---

package.json
src/pages/DatasetOnboarding/components/TextareaInputCustom/TextareaInputCustom.js

[IG-2550](https://hdruk.atlassian.net/browse/IG-2550)
react-textarea-autosize added to TextareInputCustom

IG-2550 TextareaInputCustom updated to use TextareaAutosize

---

src/HDRRouter.js
src/pages/dashboard/Components/AccountDataset/AccountDataset.js

Fixes https://hdruk.atlassian.net/browse/GAT-377

Stop react query from refetching when the window is focused

---

package.json
src/css/styles.scss
src/pages/cohort/AddEditCohortForm.js

[IG-2578](https://hdruk.atlassian.net/browse/IG-2578)
Adding react-textarea-autosize to cohorts

IG-2758 react-textarea-autosize added to cohorts

---

src/configs/ssoBtnsConfig.js
src/pages/commonComponents/LoginSSOButtons/LoginSSOButtons.jsx

Icodara 236 hiding btn microsofot login

---

src/components/Input/Input.js

story/GAT-266 - missing character breaking build

story/GAT-266 - missing character breaking build

---

src/configs/constants.js
src/pages/dashboard/Components/AccountDataset/AccountDatasetApproveModal.js
src/pages/dashboard/Components/AccountDataset/AccountDatasetRejectModal.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasets.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasets.test.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasetsContent.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasetsContent.test.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasetsTabs.js
src/pages/dashboard/Components/AccountDatasets/AccountDatasetsTabs.test.js

Release fix/gat 316 - amending / fixing sort according

Release fix/gat 316 - amending / fixing sort according

---

src/pages/collections/AddEditCollectionPage.js
src/pages/collections/CollectionPage.js
src/pages/collections/Components/ToolCollectionResults/index.js
src/pages/commonComponents/NoResults.js
src/pages/commonComponents/relatedResourcesModal/RelatedResourceModal.js
src/pages/dataUse/upload/DataUseUpload.js
src/pages/paper/AddEditPaperPage.js
src/pages/tool/AddEditToolPage.js

release-fix/GAT-732 - search breaks for data use on collection, incorrect key / index used for dataUse

release-fix/GAT-732 - seach breaks for data use on collection

---

src/pages/commonComponents/relatedResourcesModal/RelatedResourceModal.js

release-fix/GAT-730 - unable to search for related resources, incorrect value in input

release-fix/GAT-730 - unable to search for related resources

---

src/pages/collections/CollectionPage.js
src/pages/collections/collection.utils.js

Release preprod fix/gat 732 - collection search for dur (also included new fields specific to DUR records)

Release preprod fix/gat 732 - collection search for dur

---

src/pages/DatasetOnboarding/formSchema.js

release-preprod-fix/GAT-267 - Update guidance for spatial field on dataset onboarding form

release-preprod-fix/GAT-267 - Update guidance

---

src/pages/DataAccessRequest/components/DoubleDropdownCustom/DoubleDropdownCustom.js
src/pages/DataAccessRequest/components/DoubleDropdownCustom/DoubleDropdowncustom.scss
src/pages/DataAccessRequest/components/DoubleDropdownCustom/SelectedOption.scss

Release fix/gat 595 - icon incorrect for dropdown and style overriding global dropdown

Release fix/gat 595 - icon incorrect for dropdown and style overriding global dropdown

---

src/pages/DataAccessRequest/DataAccessRequest.js

@pawilliams-hdr DAR schema needs to be updated . instructions are here 
https://hdruk.atlassian.net/wiki/spaces/HDT/pages/2218590209/DAR+pre-populate

Story/GAT-756: Improving prepopulate by adding ORCID field to 'Other Individuals

---

src/pages/DataAccessRequest/components/DoubleDropdownCustom/DoubleDropdownCustom.js

release-fix/GAT-595 - Togggle doesn't work properly

release-fix/GAT-595 - Togggle doesn't work properly

---

src/pages/DatasetOnboarding/components/TypeaheadAsyncCustom/TypeaheadAsyncCustom.jsx

release-fix/GAT-770 - icon disappearing on input change

release-fix/GAT-770 - icon disappearing on input change

---

src/pages/DataAccessRequest/components/DoubleDropdownCustom/DoubleDropdownCustom.js

story/GAT-756 - Method no longer exists

story/GAT-756 - Method no longer exists

---

src/services/data-use-registers/data-use-registers.js

Story/gat 756 - incorrect dur url for check (see GAT 882)

Story/gat 756 - incorrect dur url for check

---

public/locales/en-GB/translation.json
src/pages/dataUse/DataUsePage.js

Hides the upload data use button for the personal DUR page

release-fix/GAT-928 - hide DUR upload for non-team page

---

src/pages/dataAccessRequestCustomiseForm/DataAccessRequestCustomiseForm.js
src/pages/dataAccessRequestCustomiseForm/components/CustomiseGuidance/CustomiseGuidance.js

Fix editting functionality when no guidance

Fix editting functionality when no guidance

---

src/pages/commonComponents/searchBar/UserDropdownTeams.js
src/pages/dashboard/Components/DashboardNavAccordian/DashboardNavAccordion.js
src/pages/dashboard/CustomiseDAR/CustomiseDAR.js

Added Google Analytics tags to profile drop down, custodian team dashboard and customise DAR page

Added Google Analytics tags to these items

---

src/pages/search/components/Filter.js

makes sure that filters which are checked remain highlighted and do not become greyed out

story/GAT-1103 - ensure checked filters remain highlighted

---

src/pages/dashboard/Team/AddEditTeamsPage.js

fix for creating new team --- take _id from POST and use to update question bank status

GAT-1300 - fix for creating new team

---

src/pages/commonComponents/LoginSSOButtons/LoginSSOButtons.jsx
src/pages/commonComponents/LoginSSOButtons/LoginSSOButtons.test.jsx
src/pages/commonComponents/LoginSSOButtons/__snapshots__/LoginSSOButtons.test.jsx.snap

Fixed typo in login modal

---

src/pages/DatasetOnboarding/formSchema.js

Fixing Tissue Directory bug raised by Damon

Added 'IN PROGRESS' to options in select input

---

src/pages/DataAccessRequest/components/CustodianActionButtons/CustodianActionButtons.js

Reverts HDRUK/gateway-web#1594

Revert "debugging"

---

src/pages/DatasetOnboarding/DatasetOnboarding.js
src/utils/auth.js
src/utils/auth.test.js

Reverts HDRUK/gateway-web#1617

Revert "Removed unwanted commented code and other clean up fixes"
